# Site settings
title: Fran Fabrizio's Blog
email: github@franfabrizio.com
description: > # this means to ignore newlines until "baseurl:"
  Just a blog.
baseurl: "/franfabrizio.github.io" # the subpath of your site, e.g. /blog/
url: "http://franfabrizio.github.io" # the base hostname & protocol for your site
twitter_username: franfabrizio
github_username:  franfabrizio

# Build settings
markdown: kramdown
